import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import useCoinbase from "../lib/useCoinbase";
import useRarible from "../lib/useRarible";
import useWallet from "../lib/useWallet";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  const coinbaseProvider = useCoinbase();
  const [onConnect, account] = useWallet(coinbaseProvider);
  console.log("ACCOUNT:", account);

  return (
    <div className={styles.container}>
      <Head>
        <title>Rarible SDK usage with Metamask and Coinbase wallets</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h4 className={styles.title}>
          Rarible SDK usage with Metamask and Coinbase wallets
        </h4>
        <div style={{ marginTop: "30px" }}>
          {account ? (
            account
          ) : (
            <button onClick={onConnect}>Connect Coinbase</button>
          )}
        </div>
      </main>
    </div>
  );
};

export default Home;
